# .github/workflows/deploy.yml
name: Deploy Application

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Create config.env from secret
        run: |
          echo "${{ secrets.ENV_CONFIG }}" > config.env
          cat config.env  # for debugging only; remove this in production!
      
      - name: Install dependencies
        run: npm install
      
      - name: Build and Start Application
        run: |
          npm run build  # if you have a build step; otherwise, omit
          nohup node server.js &  # start server in background
          
      # Optionally, add further deployment steps (e.g., deploying to a cloud provider)
